# Generated by Django 5.2.4 on 2025-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bookphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('paper', 'Paper'), ('ebook', 'E-book'), ('audio', 'Audio')], default='paper', max_length=10),
        ),
    ]
