# Generated by Django 5.2.4 on 2026-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_author_photo_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/authors/'),
        ),
    ]
